### ISSUE TITLE
Dependencies could not be resolved because no versions of 'GoogleAppMeasurement' match the requirement 8.12.0 and root depends on 'GoogleAppMeasurement' 8.12.0.

### ISSUE THREAD

**Issue by Azis202017** [google/GoogleAppMeasurement#20]
Dependencies could not be resolved because no versions of 'GoogleAppMeasurement' match the requirement 8.12.0 and root depends on 'GoogleAppMeasurement' 8.12.0.
Is this a bug xcode? can anyone please tell me why this happened to me?
<img width="1440" alt="Screen Shot 2022-02-05 at 06 27 04" src="https://user-images.githubusercontent.com/55499496/152616435-7c2254a2-92fd-497b-ba5f-48655d8bd288.png">
<img width="1440" alt="Screen Shot 2022-02-05 at 06 27 39" src="https://user-images.githubusercontent.com/55499496/152616480-38579e96-8ff8-4d2b-9611-e82caa536192.png">

<img width="653" alt="Screen Shot 2022-02-05 at 06 29 22" src="https://user-images.githubusercontent.com/55499496/152616605-9caad550-db77-43bc-ab47-f0bd52bee84d.png">

**Comment by paulb777** [comment]
8.12.0 has not yet been published externally. 8.11.0 is the latest supported release. 

How was the Podfile generated that is pointing at 8.12.0?

**Comment by paulb777** [comment]
Oh, I see that you're using Swift Package Manager.   Please refer to published tags instead of the master branch.

**Comment by Azis202017** [comment]
oke i'm sorry its my mistake :), I reinstall the package and its work, i will be close this issue, thank you so much
