### ISSUE TITLE
Tag `8.14.0` missing

### ISSUE THREAD

**Issue by pakko972** [google/GoogleAppMeasurement#22]
Hello, `Package.swift` refers to version `8.14.0` but this particular tag as not been published (yet?).

```
Failed to resolve dependencies
Dependencies could not be resolved because no versions of 'googleappmeasurement' match the requirement 8.14.0 and root depends on 'googleappmeasurement' 8.14.0.
```

Similar to #20

**Comment by kutsin** [comment]
Same problem

**Comment by paulb777** [comment]
Right, this is the same as #20. The 8.14.0 tag is not yet published.

**Comment by paulb777** [comment]
I'm going to close, but feel free to continue the conversation.

**Comment by bdickerson5** [comment]
I am having the same issue, but was not able to resolve it with the versioning.  Possibly an Xcode issue on my end, but any help would be great.  Full description of the issue: https://stackoverflow.com/questions/71567680/swift-package-firebase-version-not-resolving-while-using-xcworkspace-file 
Thanks,

**Comment by paulb777** [comment]
The 8.14.0 tag is now published, but this issue will continue to recur for anyone trying to access the master branch version of this repo.

**Comment by pakko972** [comment]
> The 8.14.0 tag is now published, but this issue will continue to recur for anyone trying to access the master branch version of this repo.

In my particular case, I had a dependency on the Firebase swift package, branch `master`.
Firebase master then depended on GoogleAppMeasurement 8.14.0.

So we could argue that there is more of a Firebase issue.

**Comment by paulb777** [comment]
Firebase does not currently support using SwiftPM from the master branch. It only supports using it via release tags.
