### ISSUE TITLE
no versions of 'GoogleAppMeasurement' match the requirement 8.15.0

### ISSUE THREAD

**Issue by douglasrosa0110** [google/GoogleAppMeasurement#24]
```
Fetching from https://github.com/google/promises.git

Dependencies could not be resolved because no versions of 'GoogleAppMeasurement' match the requirement 8.15.0 and root depends on 'GoogleAppMeasurement' 8.15.0.

xcodebuild: error: Could not resolve package dependencies:
  Dependencies could not be resolved because no versions of 'GoogleAppMeasurement' match the requirement 8.15.0 and root depends on 'GoogleAppMeasurement' 8.15.0.

##[error]Error: /usr/bin/xcodebuild failed with return code: 74
```

**Comment by ryanwilson** [comment]
Hey @douglasrosa0110 - thanks for the report. Can you please share how you saw the error? Are you trying to point to Firebase on the `master` branch? We have a temporary mismatch of versions between preparing a release and publishing, if you share your use case it'll help us figure out how to reduce the amount of side-effects in the future.

Regardless, I'm just about to publish version 8.15.0 so it should go away shortly (I'll close this when it's published). Thanks!

**Comment by douglasrosa0110** [comment]
@ryanwilson Thanks for your promply reply!

We are implementing the CI in the appcenter and have get this error.
As you said and in other issues closed yet, we will try add a fixed version instead the master branch.

Thanks a lot!

**Comment by ryanwilson** [comment]
Just published! Thanks for the info. If using `master` is a requirement - we use an environment variable to modify the GoogleAppMeasurement dependency to point to the `main` branch on that repo. No promises that it'll stay the same, but may be a reasonable workaround if you're still hoping to stay on `master`.

https://github.com/firebase/firebase-ios-sdk/blob/2cbb180697105c451497901a918f9c6fb7a5372f/Package.swift#L1280-L1289
