### ISSUE TITLE
GoogleAppMeasurementOnDeviceConversion.xcframework possibly not including Mac Catalyst

### ISSUE THREAD

**Issue by kamalWam** [google/GoogleAppMeasurement#33]
GoogleAppMeasurementOnDeviceConversion.xcframework:1:1: error: While building for Mac Catalyst, no library for this platform was found in '.....GoogleAppMeasurementOnDeviceConversion.xcframework'. (in target 'GoogleAppMeasurementOnDeviceConversion' from project 'GoogleAppMeasurement')

**Comment by paulb777** [comment]
OnDeviceConversion is currently only supported for iOS.

**Comment by vennyvirtuoso** [comment]
> 

is this occurring because of architecture difference of apple silicon and the framework?

**Comment by ncooke3** [comment]
This is likely appearing because the `FirebaseAnalyticsOnDeviceConversion.xcframework` is being used in a scheme building for macCatalyst. As Paul said, the FirebaseAnalyticsOnDeviceConversion SDK is only supported for iOS, and should be excluded in Catalyst builds.
