### ISSUE TITLE
 does not contain bitcode

### ISSUE THREAD

**Issue by HAL-JP** [google/GoogleAppMeasurement#36]
GoogleAppMeasurement.framework/GoogleAppMeasurement(APMEventAggregates.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/haru/Library/Developer/Xcode/DerivedData/Unity-iPhone-cuotwyogvxfhadenpzxqztkjdlfr/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/WithoutAdIdSupport/GoogleAppMeasurement.framework/GoogleAppMeasurement' for architecture arm64

**Comment by paulb777** [comment]
Bitcode was removed in the 10.1.0 release because it is no longer supported by Xcode 14.

It's recommended to remove bitcode from your Build Settings.

If you still want to use bitcode in an Xcode 13 build, stick with an earlier Firebase release.
