### ISSUE TITLE
many crash on GoogleAppMeasurement 9.6.0

### ISSUE THREAD

**Issue by ipangth** [google/GoogleAppMeasurement#37]
after out app ugrade google ad sdk to  - Google-Mobile-Ads-SDK (= 9.11.0), GoogleAppMeasurement (= 9.6.0), there much crash on. But previous version (   Google-Mobile-Ads-SDK (8.13.0) GoogleAppMeasurement (8.10.0):) is OK.

0 libsystem_blocks.dylib 0x000000020bcd3afc __Block_copy + 56
1 libdispatch.dylib 0x00000001c624c478 __dispatch_Block_copy + 32
2 libdispatch.dylib 0x00000001c624c478 __dispatch_Block_copy + 32
3 libdispatch.dylib 0x00000001c62658e0 _dispatch_after + 280
4 QQKSong 0x0000000103bfbcb0 -[APMPersistedConfig scheduleSynchronizeToDisk] + 168
5 libdispatch.dylib 0x00000001c624dfdc __dispatch_client_callout + 20
6 libdispatch.dylib 0x00000001c625d574 __dispatch_lane_barrier_sync_invoke_and_complete + 56
7 QQKSong 0x0000000103bfb90c -[APMPersistedConfig setString:forKey:] + 136
8 QQKSong 0x0000000103bada04 -[APMIdentity enforceConsentSettings] + 60
9 QQKSong 0x0000000103baea80 ___32-[APMIdentity updateIdentifiers]_block_invoke + 72
10 libdispatch.dylib 0x00000001c624c4b4 __dispatch_call_block_and_release + 32
11 libdispatch.dylib 0x00000001c624dfdc __dispatch_client_callout + 20
12 libdispatch.dylib 0x00000001c6255694 __dispatch_lane_serial_drain + 672
13 libdispatch.dylib 0x00000001c62561e0 __dispatch_lane_invoke + 384
14 libdispatch.dylib 0x00000001c6260e10 __dispatch_workloop_worker_thread + 652
15 libsystem_pthread.dylib 0x000000020bcd7df8 __pthread_wqthread + 288
SEGV_ACCERR
Issue ID：B8406351C0E70EB236028468F644741C

0
libdispatch.dylib
__dispatch_block_async_invoke2 + 60
1
libdispatch.dylib
__dispatch_client_callout + 20
2
libdispatch.dylib
__dispatch_client_callout + 20
3
libdispatch.dylib
__dispatch_continuation_pop + 504
4
libdispatch.dylib
__dispatch_source_invoke + 1588
5
libdispatch.dylib
__dispatch_lane_serial_drain + 376
6
libdispatch.dylib
__dispatch_lane_invoke + 384
7
libdispatch.dylib
__dispatch_workloop_worker_thread + 652
8
libsystem_pthread.dylib
__pthread_wqthread + 288

**Comment by paulb777** [comment]
This issue is tracked at https://github.com/firebase/firebase-ios-sdk/issues/10495
