### ISSUE TITLE
Usage of depreciated CC_MD5 algorithm  

### ISSUE THREAD

**Issue by ydharaiya-intuit** [google/GoogleAppMeasurement#39]
Hi Google Team,
We are writing this mail a request you update the usage of depreciated crypto API CC_MD5 with SHA256 in GoogleAppMeasurement.xcframework. This is being flagged in multiple places throughout our project as a security vulnerability via multiple SAST tools. Would really appreciate your help. Here attaching some screenshots for your reference.

**Comment by paulb777** [comment]
This is a duplicate of https://github.com/firebase/firebase-ios-sdk/issues/8519

**Comment by ydharaiya-intuit** [comment]
Hi @paulb777 ,
Even though this issue is not an urgent requirement in 2021 do you see in any need to update this since CC_MD5 is now deprecated? if apple decides to make CC_MD5 obsolete then this can be a big issue and can be a problem for project compilation
