### ISSUE TITLE
10.24.0 does not have a release

### ISSUE THREAD

**Issue by erikkrietsch** [google/GoogleAppMeasurement#70]
Hello! I was poking around and noticed that [this PR](https://github.com/google/GoogleAppMeasurement/pull/69) mentioned releasing 10.24.0, but there isn't a corresponding [release](https://github.com/google/GoogleAppMeasurement/releases) or tag with that version.  Thanks!

edit: why I noticed, and why it matters is that I was attempting to build the firebase-ios-sdk and got this error: 
<img width="810" alt="image" src="https://github.com/google/GoogleAppMeasurement/assets/1254162/a194b235-3a1f-4559-84e1-c571106bcb92">

**Comment by ncooke3** [comment]
Hi @erikkrietsch, GoogleAppMeasurement is released in sync with Firebase. Firebase 10.24.0 will be released this week.
